services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortlinks
    ports:
      - "5432:5432" 
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 2links-container
    env_file:
      - ./cmd/.env
    ports:
      - "${PORT:-8090}:${PORT:-8090}"
    depends_on:
      - postgres

volumes:
  postgres-data: